Journey/Tour/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('travello.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]
if settings.DEBUG:
     urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
     urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Journey/accounts/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    first_name = models.CharField(max_length = 30, null=True, blank=True)
    last_name  = models.CharField(max_length = 30, null=True, blank=True)
    email      = models.EmailField(max_length = 30, null=True, blank=True)
    username   = models.CharField(max_length = 30, null=True, blank=True)
    mob        = models.CharField(max_length = 10)
    password = models.CharField(max_length=8, null=False, blank=False)
    image = models.FileField()
    

    def __str__(self):
        return self.username

Journey/templates/contact.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png">
	<title>Contact Us</title>
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'vendors/linericon/style.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'vendors/nice-select/css/nice-select.css' %}">
	<!-- main css -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>

	<!--================ Start Header Menu Area =================-->
	<header class="header_area">
		<div class="main_menu">
			<nav class="navbar navbar-expand-lg navbar-light">
				<div class="container">
					<!-- Brand and toggle get grouped for better mobile display -->
					<a class="navbar-brand logo_h" href="index.html"><img src="img/logo.png" alt=""></a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
					 aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
						<ul class="nav navbar-nav menu_nav ml-auto">
							<li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Home</a></li>
							<li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Register</a></li>
							<li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
							<li class="nav-item"><a class="nav-link" href="{% url 'contact' %}">Contact</a></li>
						</ul>
						<ul class="nav navbar-nav ml-auto">
	
							<li class="nav-item">
								<button type="button" class="search nav-link">
									<i class="lnr lnr-magnifier" id="search"></i>
								</button>
							</li>
						</ul>
					</div>
				</div>
			</nav>
			
			<div class="search_input" id="search_input_box">
				<div class="container">
					<form class="d-flex justify-content-between">
						<input type="text" class="form-control" id="search_input" placeholder="Search Here">
						<button type="submit" class="btn"></button>
						<span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
					</form>
				</div>
			</div>
		</div>
	</header>
	<!--================ End Header Menu Area =================-->

	<!--================Home Banner Area =================-->
	<section class="banner_area ">
		<div class="banner_inner overlay d-flex align-items-center">
			<div class="container">
				<div class="banner_content">
					<div class="page_link">
						<a href="index.html">Home</a>
						<a href="contact.html">Contact Us</a>
					</div>
					<h2>Contact Us</h2>
				</div>
			</div>
		</div>
	</section>
	<!--================End Home Banner Area =================-->

	<!--================Contact Area =================-->
	<section class="contact_area section_gap">
		<div class="container">
			<div id="mapBox" class="mapBox" data-lat="40.701083" data-lon="-74.1522848" data-zoom="13" data-info="PO Box CT16122 Collins Street West, Victoria 8007, Australia."
			 data-mlat="40.701083" data-mlon="-74.1522848">
			</div>
			<div class="row">
				<div class="col-lg-3">
					<div class="contact_info">
						<div class="info_item">
							<i class="lnr lnr-home"></i>
							<h6>California, United States</h6>
							<p>Santa monica bullevard</p>
						</div>
						<div class="info_item">
							<i class="lnr lnr-phone-handset"></i>
							<h6><a href="#">00 (440) 9865 562</a></h6>
							<p>Mon to Fri 9am to 6 pm</p>
						</div>
						<div class="info_item">
							<i class="lnr lnr-envelope"></i>
							<h6><a href="#">support@colorlib.com</a></h6>
							<p>Send us your query anytime!</p>
						</div>
					</div>
				</div>
				<div class="col-lg-9">
					<form class="row contact_form" action="contact_process.php" method="post" id="contactForm" novalidate="novalidate">
						<div class="col-md-6">
							<div class="form-group">
								<input type="text" class="form-control" id="name" name="name" placeholder="Enter your name">
							</div>
							<div class="form-group">
								<input type="email" class="form-control" id="email" name="email" placeholder="Enter email address">
							</div>
							<div class="form-group">
								<input type="text" class="form-control" id="subject" name="subject" placeholder="Enter Subject">
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<textarea class="form-control" name="message" id="message" rows="1" placeholder="Enter Message"></textarea>
							</div>
						</div>
						<div class="col-md-12 text-right">
							<button type="submit" value="submit" class="primary-btn text-uppercase">Send Message</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</section>
	<!--================Contact Area =================-->

	<!--================  start footer Area =================-->
	<footer class="footer-area">
		<div class="footer_top section_gap_top">
			<div class="container">
				<div class="row">
					<div class="col-lg-3 col-md-6 col-sm-6">
						<div class="single-footer-widget">
							<h5 class="footer_title">About Agency</h5>
							<p class="about-text">The world has become so fast paced that people don’t want to stand by reading a page of information, they would much rather look at a presentation and understand the message. It has come to a point where images and videos are used more to </p>
						</div>
					</div>
					<div class="col-lg-2 col-md-6 col-sm-6">
						<div class="single-footer-widget">
							<h5 class="footer_title">Navigation Links</h5>
							<div class="row">
								<div class="col-5">
									<ul class="list">
										<li><a href="#">Home</a></li>
										<li><a href="#">Features</a></li>
										<li><a href="#">Services</a></li>
										<li><a href="#">Portfolio</a></li>
									</ul>
								</div>
								<div class="col-5">
									<ul class="list">
										<li><a href="#">Team</a></li>
										<li><a href="#">Pricing</a></li>
										<li><a href="#">Blog</a></li>
										<li><a href="#">contact</a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-3 col-md-6 col-sm-6">
						<div class="single-footer-widget">
							<h5>Newsletter</h5>
							<p>For business professionals caught between high OEM price and mediocre print and graphic output, </p>
							<div class="footer-newsletter" id="mc_embed_signup">	
								<form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
								 method="get" class="form-inline">
									<div class="d-flex flex-row">
										<input class="form-control" name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '"
										 required="" type="email">
										<button class="click-btn btn btn-default"><span class="lnr lnr-location" aria-hidden="true"></span></button>
										<div style="position: absolute; left: -5000px;">
											<input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
										</div>
									</div>
									<div class="info"></div>
								</form>
							</div>
						</div>
					</div>
					<div class="col-lg-3  col-md-6 col-sm-6">
						<div class="single-footer-widget mail-chimp">
							<h5 class="mb-20">Instragram Feed</h5>
							<ul class="instafeed d-flex flex-wrap">
								<li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
								<li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
								<li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
								<li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
								<li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
								<li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
								<li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
								<li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="copyright">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 col-md-12">
						<p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</p>
					</div>
					<div class="col-lg-6 col-md-12 text-right">
						<div class="social-icons">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<!--================ End footer Area =================-->

	<!--================Contact Success and Error message Area =================-->
	<div id="success" class="modal modal-message fade" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<i class="fa fa-close"></i>
					</button>
					<h2>Thank you</h2>
					<p>Your message is successfully sent...</p>
				</div>
			</div>
		</div>
	</div>

	<!-- Modals error -->

	<div id="error" class="modal modal-message fade" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<i class="fa fa-close"></i>
					</button>
					<h2>Sorry !</h2>
					<p> Something went wrong </p>
				</div>
			</div>
		</div>
	</div>
	<!--================End Contact Success and Error message Area =================-->

	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/popper.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/stellar.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
	<script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
	<script src="{% static 'js/mail-script.js' %}"></script>
	<!--gmaps Js-->
	<script src="{% static 'https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE' %}"></script>
	<script src="{% static 'js/gmaps.min.js' %}"></script>
	<script src="{% static 'js/theme.js' %}"></script>
</body>

</html>

Journey/templates/dpt.html
{% load static %}
<!DOCTYPE html>
<html lang='en'>
<head>
    <title> Departments </title>
</head>
<h1> Select a Department </h1>
<body bgcolor=#4DD0E1 align="center">
    <form action='login' method='POST'>
        {% csrf_token %}
        {% for field in dpt %}
        <br>
        {{ field.label }}
        {{ field }}
        {% endfor %}
        <br>
        <br>
        <button type='submit'>submit</button>
    </form>
</body>
</html>

Journey/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title> Login </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"</head>
<style>
body{
    background-image:url(https://www.britishairways.com/assets/images/MediaHub/Media-Database/Royalty-free-RF/Destinations/Mauritius-MRU/185241201_1200x675.jpg);
    background-size:cover;
}
big{
    color: brown;
}
</style>
</head>
<div class="container" style="margin: 20px">
    <div class="row">
            <button class="btn btn-light btn-md"><a href="{% url 'index' %}" name='index'  title='index'>Home</a></button>
        </div>
    </div>
</div><br><br><br>
<body>
    <form method='POST'>
        {% csrf_token %}
        <div class='container' style="margin-top: 120px">
            <input class='form-control' type='text' name='username' placeholder=' Enter Username' required><br>
            <input class='form-control' type='password' name='password' placeholder=' Enter Password' required><br>
            <button class="btn btn-primary btn-sm" type="submit" title="submit">Login</button><br><br>
            <small style="color: beige">Not Regisered yet? <big><a href='register' name='register'  title='register'>Register</a></big>Here Now</small>
        </div>
    </form>
</body>
</html>

Journey/templates/logout.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title> Logout </title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/logout_styles.css' %}">
</head>
<body bgcolor=#9CCC65 >
    <h1> Thank You, Visit again</h1>
    <form action='logout' method='POST'>
        {% csrf_token %}
    </form>
</body>
</html>

Journey/templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Navbar</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>
<body>
<div class="container">
  <h2>Basic Table</h2>
  <p>The .table class adds basic styling (light padding and horizontal dividers) to a table:</p>            
  <table class="table">
    <thead class='thead-light'>
      <tr class='table-bordered'>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <tr class='table-primary'>
        <td>John</td>
        <td>Doe</td>
        <td>john@example.com</td>
      </tr>
      <tr class='table-secondary'>
        <td>Mary</td>
        <td>Moe</td>
        <td>mary@example.com</td>
      </tr>
      <tr class='table-success'>
        <td>July</td>
        <td>Dooley</td>
        <td>july@example.com</td>
      </tr>
    </tbody>
  </table>
</div>

  <form>
  <div class="container">
    <h2>Pagination</h2>
    <p>To create a basic pagination, add the .pagination class to an ul element. Then add the .page-item to each li element and a .page-link class to each link inside li:</p>                  
    <ul class="pagination">
        <li class="page-item"><a class="page-link" href="www.google.com">Previous</a></li>
        <li class="page-item"><a class="page-link" href="success">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul>
    </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a><br><br>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">click</span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            </ul>
        </div>
        
  </form>
  
</nav>
</body>
</html>

Journey/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <!-- <link rel="stylesheet" href="signup.css"> -->
     <link rel="icon" href="https://freeicons.io/laravel/public/uploads/icons/png/20516227111558424399-512.png">
    <title>SignUp</title>
</head>
<div class="container" style="margin: 20px">
        <div class="row">
                <button class="btn btn-light btn-md"><a href="{% url 'index' %}" name='index'  title='index'>Home</a></button>
            </div>
        </div>
</div>
<body>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
      {{form.as_p}}
      confirm_password:<input type="password" name="confirm_password" required id="confirm_password">
        <input type="submit" value='submit'/>
        <!-- <button class="btn btn-light btn-md"><a href="{% url 'index' %}" name='index'  title='index'>Home</a></button> --> 
      {% if messages %}
        {% for msg in messages %}
        <p>{{msg}}</p>
        {% endfor %}
        {% endif %}
         <!-- <div class="container">
            <div  class="row">
                <div class="col-md-4">
                    <label for="id_first_name">First name:</label> <input type="text" name="first_name" id="id_first_name">
                </div>&nbsp;
                <div class="col-md-4">
                    <label for="id_last_name">Last name:</label> <input type="text" name="last_name" id="id_last_name">
                </div>
            </div><br>
            <div  class="row">
                <div class="col-md-6">
                    <label for="id_email">Email:</label> <input type="email" name="email" id="id_email">
                </div>
            </div><br>
            <div  class="row">
                <div class="col-md-4">
                    <label for="id_username">Username:</label><br> <input type="text" name="username" id="id_username">
                </div>
                <div class="col-md-4">
                    <label for="id_mob">Mobile:</label><br> <input type="text" name="mob" required id="id_mob">
                </div>
            </div><br>
            <div  class="row">
                <div class="col-md-4">
                    <label for="id_password">Password:</label> <input type="password" name="password" required id="id_password">
                </div>
                <div class="col-md-4">
                    <label for="confirm_password">confirm_password:</label> <input type="password" name="confirm_password" required id="confirm_password">
                    </div>
                    <img src="{{ user.image.url }}">
            </div><br>
                        <input class='btn btn-outline-warning btn-sm' type="submit" title='signup'/><br><br>
                        <div class='col-md-6'>
                            <small>Already a User <a href='login' name='login'  title='login'>Login</a> Here</small>
                        </div>
        </div> -->
    </form>
<style>
body{
    background-image:url('https://techbeacon.scdn7.secure.raxcdn.com/sites/default/files/styles/article_hero_image/public/field/image/coding-programming-key-test-automation-engineer-career_0.jpg?itok=-CR3XCQ2');
    /* background-color: beige; */
    font-family:'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
    letter-spacing: 2px;
    background-repeat: no-repeat;
    background-size: cover;
    margin-top: 80px;
}
small{
    color:whitesmoke;
    margin: -3%;
}
.btn.btn-primary {
    background-color: rgb(245, 206, 34);
}

a{
    color:yellowgreen;
}
label{
    backface-visibility: hidden;
    font-size: 0.8rem !important;
    top: 0.1rem !important;
    color:violet;
    font-weight: 600;
}
.row {
    width: 95%;
}

input#id_last_name {
    width: 100%;
}
input#id_first_name {
    width: 100%;
}
input#id_usrname {
    width: 100%;
}input#id_mobile {
    width: 100%;
}
input#id_email {
    width: 100%;
}
input#id_password {
    width: 100%;
}
input.btn.btn-primary {
    width: 10%;
    background-color: rgb(245, 206, 34);
}
.col-md-12 {
    margin: 33px;
}
</style>
</body>
</html>

Journey/templates/success.html
<head>
    <title> You are in </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    
<body bgcolor=#CFD8DC>
<style>
body{
    background-image:url('https://image.shutterstock.com/image-vector/welcome-poster-spectrum-brush-strokes-260nw-1146069941.jpg');
    background-size:cover;
}
.jumbotron jumbotron-fluid{
    padding:0px 500px 0px 400px;
}
</style>

<div class="container">
  
    </li>
    <ul class="nav nav-tabs nav-pills">
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'index' %}">Home</a>
    </li>
  </ul>
</div>
<form action='logout'>
    <div class="alert alert-success">
        <strong>Successfully!</strong> Logged In.
    </div>
</form>
</body>

Journey/templates/to_get.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <table>
        <tr>
            <th>S.no</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Username</th>
            <th>Mobile</th>
            <th>Password</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        {% for vis in hat %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{vis.first_name}}</td>
            <td>{{vis.last_name}}</td>
            <td>{{vis.username}}</td>
            <td>{{vis.email}}</td>
            <td>{{vis.mob}}</td>
            <td>{{vis.password}}</td>
            <td><a href="{% url 'to_update' vis.pk %}">edit</a></td>
            <td><a href="{% url 'to_delete' vis.pk %}">delete</a></td>
        </tr>
        {% endfor %}
</body>
</html>